# Generated by Django 5.2.7 on 2025-10-22 10:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('flat', 'Flat Discount'), ('percent', 'Percentage Discount')], default='flat', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prepare_time', models.PositiveIntegerField(default=10, help_text='Time in minutes')),
                ('is_veg', models.BooleanField(default=False)),
                ('is_non_veg', models.BooleanField(default=False)),
                ('is_eggetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('quantity_value', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('quantity_unit', models.CharField(choices=[('pcs', 'Pieces'), ('item', 'Item'), ('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Millilitre'), ('lt', 'Litre'), ('lb', 'Pound'), ('cup', 'Cup'), ('other', 'Other (Custom Input)')], max_length=20)),
                ('custom_unit_value', models.CharField(blank=True, help_text="Enter only if 'Other' selected", max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_symbol', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'British Pound (£)'), ('other', 'Other (Custom Input)')], default='₹', max_length=10)),
                ('custom_currency_symbol', models.CharField(blank=True, help_text="Enter only if 'Other' selected", max_length=10, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock_available', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_order_quantity', models.PositiveIntegerField(default=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('customizations', models.TextField(blank=True, help_text='Custom options or instructions', null=True)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurant.maincategory')),
                ('offers', models.ManyToManyField(blank=True, related_name='products', to='restaurant.offer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_items/')),
                ('alt_text', models.CharField(blank=True, max_length=120, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_main_image', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurant.productitem')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='restaurant.maincategory')),
            ],
            options={
                'unique_together': {('main_category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='restaurant.subcategory'),
        ),
    ]
