# Generated by Django 5.2.7 on 2025-10-23 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='custom_currency_symbol',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='custom_unit_value',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='featured_order',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_eggetarian',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_non_veg',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_veg',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_vegan',
        ),
        migrations.AddField(
            model_name='productitem',
            name='variant_type',
            field=models.CharField(choices=[('Veg', 'VEG'), ('Non-Veg', 'NON-VEG'), ('Eggetarian', 'EGGETARIAN'), ('Vegan', 'VEGAN'), ('None', 'NONE')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='currency_symbol',
            field=models.CharField(choices=[('$', 'US Dollar ($)'), ('₹', 'Indian Rupee (₹)'), ('€', 'Euro (€)'), ('£', 'British Pound (£)')], default='$', max_length=10),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity_unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('item', 'Item'), ('lb', 'Pound'), ('oz', 'Ounce'), ('kg', 'Kilogram'), ('g', 'Gram'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('ml', 'Millilitre'), ('l', 'Litre'), ('fl oz', 'Fluid Ounce'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('bottle', 'Bottle'), ('can', 'Can'), ('jar', 'Jar'), ('pack', 'Pack'), ('slice', 'Slice')], default='item', max_length=20),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity_value',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
