# Generated by Django 5.2.7 on 2025-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_productitem_custom_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='productitem',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity_unit',
            field=models.CharField(choices=[('item', 'Item'), ('pcs', 'Pieces'), ('plate', 'Plate'), ('bowl', 'Bowl'), ('slice', 'Slice'), ('pack', 'Pack'), ('box', 'Box'), ('cup', 'Cup'), ('ml', 'Millilitre'), ('l', 'Litre'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('bottle', 'Bottle'), ('can', 'Can'), ('jar', 'Jar'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
