# Generated by Django 5.2.7 on 2025-10-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_maincategory_options_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['main_category', 'display_order']},
        ),
    ]
