# Generated by Django 5.2.7 on 2025-10-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['display_order']},
        ),
    ]
