# Generated by Django 5.2.7 on 2025-11-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility/SEO', max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
