# Generated by Django 5.2.7 on 2025-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_productitem_image_productitem_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity_unit',
            field=models.CharField(choices=[('item', 'Item'), ('pcs', 'Pieces'), ('plate', 'Plate'), ('bowl', 'Bowl'), ('slice', 'Slice'), ('pack', 'Pack'), ('box', 'Box'), ('cup', 'Cup'), ('glass', 'Glass'), ('ml', 'Millilitre'), ('l', 'Litre'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('bottle', 'Bottle'), ('can', 'Can'), ('jar', 'Jar'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
