# Generated by Django 5.2.7 on 2025-11-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_maincategory_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
