# Generated by Django 5.2.7 on 2025-11-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_maincategory_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
    ]
