# Generated by Django 5.2.7 on 2025-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterField(
            model_name='productitem',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('main_category', 'name')},
        ),
    ]
