# Generated by Django 5.2.7 on 2025-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_maincategory_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='quantity_unit',
            field=models.CharField(choices=[('item', 'Item'), ('pcs', 'Pieces'), ('plate', 'Plate'), ('bowl', 'Bowl'), ('cup', 'Cup'), ('glass', 'Glass'), ('ml', 'ml'), ('l', 'Litre'), ('g', 'Gram'), ('kg', 'Kg'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
