# Generated by Django 5.2.7 on 2025-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='role_category',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('customer', 'Customer')], default='customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_category',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('customer', 'Customer')], default='customer', max_length=100),
        ),
    ]
